[project]
name = "downloader-cli"
version = "1.0.0"
description = "Downloader CLI"
authors = [
    { name = "tadeasf", email = "taddy.fort@gmail.com" }
]
dependencies = [
    "python-dotenv>=0.9.0",
    "typer>=0.9.0",
    "pyaml>=5.3",
    "toml>=0.10.0",
    "prompt-toolkit>=3.0.0",
    "ipaddress>=1.0.22",
    "requests>=2.25.0",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/downloader_cli"]

[project.scripts]
downloader-cli = "downloader_cli.main:app"
